name: hadolint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so the job can access it.
      - uses: actions/checkout@v3
    
      # Hadolint is a linter for the Dockerfile.
      - name: Hadolint Action
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
