name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      # Checks out repository, so the job can access it.
      - uses: actions/checkout@v3
    
      - name: Hadolint linter checks Dockerfile.
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Installs dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lints with ruff
        run: |
          # Stops the build if there are Python syntax errors or undefined names.
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
          # Uses default set of ruff rules with GitHub Annotations.
          ruff --format=github --target-version=py310 .
