name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      # Checks out repository, so the job can access it.
      - uses: actions/checkout@v3
    
      - name: Hadolint Linter for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Python Linters
        uses: wearerequired/lint-action@v2
        with:
          autopep8: true
